version: '3.7'

services:
  dev: &dev
    build:
      context: .
      target: dev_img
    volumes:
      - './:/go/src/mockd'
  prod:
    <<: *dev
    build:
      context: .
      target: prod_img
    environment:
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASS=postgres
      - TABLE=foo
      - ENGINE=postgres
      - PGPORT=5432
      - ROWS=1000
  
  postgres:
    build:
      context: pgtestdb
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD
      - POSTGRES_DB=postgres

    