version: '3.7'

services:
  dev: &dev
    build:
      context: .
      target: dev_img
    volumes:
      - './:/go/src/mockd'
  prod:
    <<: *dev
    build:
      context: .
      target: prod_img
    environment:
      - PGHOST=postgres
      - PGDATABASE=gpadmin
      - PGUSER=gpadmin
      - PGPASS=gpadmin
      - TABLE=foo
      - ENGINE=postgres
      - PGPORT=5432
  
  postgres:
    build:
      context: pgtestdb
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=gpadmin
      - POSTGRES_PASSWORD=gpadmin
      - POSTGRES_DB=gpadmin
      - PGDATA=/usr/local/var/postgres
    volumes:
      - pgdata:/usr/local/var/postgres
volumes:
  pgdata:
    external: true
    